apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-mediawiki
  namespace: mediawiki

spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-mediawiki
  template:
    metadata:
      labels:
        app: deploy-mediawiki
    spec:
      containers:
      - name: deploy-mediawiki
        image: maheshlakade148/mediawiki:latest
        env:
        - name: DocumentRoot
          value: "/var/www/mediawiki"
---
apiVersion: v1
kind: Service
metadata:
  name: poc-mediawiki
  namespace: mediawiki

spec:
  ports:
  - port: 3001
    targetPort: 80
    protocol: TCP
  selector:
    app: deploy-mediawiki
  type: LoadBalancer
 
---
