FROM mariadb:latest
#MAINTAINER maheshlakade148@gmail.com

ENV MYSQL_ROOT_PASSWORD root@test123
ENV MYSQL_DATABASE wikidatabase 
ENV MYSQL_USER wiki
ENV MYSQL_PASSWORD root@test123

EXPOSE 3306
CMD ["mysqld"]
